# Generated by Django 4.1.5 on 2023-01-24 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0002_alter_schools_schoolid_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Schools',
            new_name='School',
        ),
    ]
