# Generated by Django 4.1.5 on 2023-01-25 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0004_aspiration_path_race_rename_school_name_school_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquippedSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheet.character')),
                ('intrinsic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sheet.skill')),
                ('main_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sheet.skill')),
                ('main_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sheet.skill')),
                ('main_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sheet.skill')),
                ('main_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sheet.skill')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sheet.skill')),
                ('perfect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sheet.skill')),
                ('reaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sheet.skill')),
                ('support_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sheet.skill')),
                ('support_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sheet.skill')),
            ],
        ),
        migrations.CreateModel(
            name='AvailableSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheet.character')),
                ('skill_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheet.skill')),
            ],
        ),
        migrations.CreateModel(
            name='AvailablePath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_pp', models.PositiveIntegerField()),
                ('total_pp', models.PositiveIntegerField()),
                ('level', models.PositiveSmallIntegerField()),
                ('is_master', models.BooleanField(default=False)),
                ('char_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheet.character')),
                ('path_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheet.path')),
            ],
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('C', 'CORPO'), ('M', 'MENTE'), ('F', 'FOCO'), ('E', 'ESPÍRITO'), ('S', 'SOCIAL'), ('N', 'NATUREZA')], max_length=1)),
                ('current_value', models.PositiveIntegerField()),
                ('total_value', models.PositiveIntegerField()),
                ('temp_value', models.PositiveIntegerField()),
                ('training_level', models.PositiveSmallIntegerField()),
                ('char_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheet.character')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('A', 'ACERTAR'), ('E', 'ESQUIVAR'), ('D', 'DEFENDER'), ('R', 'RESISTIR'), ('C', 'CANALIZAR')], max_length=1)),
                ('nd4', models.PositiveIntegerField()),
                ('nd6', models.PositiveIntegerField()),
                ('nd8', models.PositiveIntegerField()),
                ('nd10', models.PositiveIntegerField()),
                ('nd12', models.PositiveIntegerField()),
                ('nd20', models.PositiveIntegerField()),
                ('flat_bonus', models.PositiveIntegerField()),
                ('flat_penalty', models.PositiveIntegerField()),
                ('char_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheet.character')),
            ],
        ),
    ]
