# Generated by Django 4.1.5 on 2023-01-26 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0006_alter_character_annotations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equippedskill',
            name='id',
        ),
        migrations.AlterField(
            model_name='equippedskill',
            name='char_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sheet.character'),
        ),
    ]
