# Generated by Django 4.1.5 on 2023-01-26 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0007_remove_equippedskill_id_alter_equippedskill_char_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equippedskill',
            name='char_ID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sheet.character'),
        ),
    ]
