# Generated by Django 4.1.5 on 2023-01-26 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0009_alter_equippedskill_intrinsic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equippedskill',
            name='intrinsic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sheet.skill'),
        ),
        migrations.AlterField(
            model_name='equippedskill',
            name='main_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sheet.skill'),
        ),
        migrations.AlterField(
            model_name='equippedskill',
            name='main_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sheet.skill'),
        ),
        migrations.AlterField(
            model_name='equippedskill',
            name='main_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sheet.skill'),
        ),
        migrations.AlterField(
            model_name='equippedskill',
            name='main_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sheet.skill'),
        ),
        migrations.AlterField(
            model_name='equippedskill',
            name='movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sheet.skill'),
        ),
        migrations.AlterField(
            model_name='equippedskill',
            name='perfect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sheet.skill'),
        ),
        migrations.AlterField(
            model_name='equippedskill',
            name='reaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sheet.skill'),
        ),
        migrations.AlterField(
            model_name='equippedskill',
            name='support_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sheet.skill'),
        ),
        migrations.AlterField(
            model_name='equippedskill',
            name='support_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sheet.skill'),
        ),
    ]
