# Generated by Django 4.1.5 on 2023-01-26 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0010_alter_equippedskill_intrinsic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='type',
            new_name='_type',
        ),
    ]
