# Generated by Django 4.1.5 on 2023-01-27 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0011_rename_type_action__type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute',
            old_name='type',
            new_name='_type',
        ),
    ]
