# Generated by Django 4.1.5 on 2023-01-28 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sheet', '0012_rename_type_attribute__type'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='player_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
