# Generated by Django 4.1.5 on 2023-02-01 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0013_character_player_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='category',
            new_name='_category',
        ),
    ]
