# Generated by Django 4.1.5 on 2023-02-09 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0014_rename_category_skill__category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equippedskill',
            old_name='main_1',
            new_name='general_1',
        ),
        migrations.RenameField(
            model_name='equippedskill',
            old_name='main_2',
            new_name='general_2',
        ),
        migrations.RenameField(
            model_name='equippedskill',
            old_name='main_3',
            new_name='general_3',
        ),
        migrations.RenameField(
            model_name='equippedskill',
            old_name='main_4',
            new_name='general_4',
        ),
    ]
