# Generated by Django 4.1.5 on 2023-02-16 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0015_rename_main_1_equippedskill_general_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='main_action_cost',
            field=models.IntegerField(default=3000),
        ),
        migrations.AddField(
            model_name='character',
            name='movement_action_cost',
            field=models.IntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='path',
            name='tier',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Provisional'), (1, 'Basic'), (2, 'Advanced'), (3, 'Specialist')], default=1),
        ),
        migrations.AlterField(
            model_name='skill',
            name='_category',
            field=models.CharField(choices=[('ITS', 'Intrinsic'), ('GEN', 'General'), ('SUP', 'Support'), ('REA', 'Reaction'), ('MOV', 'Movement'), ('PER', 'Perfect')], default='GEN', max_length=3),
        ),
    ]
