# Generated by Django 4.1.5 on 2023-02-23 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0016_character_main_action_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='attribute_point_cost',
            field=models.PositiveIntegerField(default=400),
        ),
        migrations.AddField(
            model_name='attribute',
            name='training_cost',
            field=models.PositiveIntegerField(default=500),
        ),
    ]
